version: '2'
services:
 nginx:
  build: .
  depends_on:
  - php
  ports:
    - "8083:80"
 php:
   image: php:fpm
   command: /bin/sh /var/www/start.sh
   volumes:
    - ./start.sh:/var/www/start.sh
    - ./web/uploadfiles:/var/www/html/uploadfiles
    - ./web:/var/www/html
    - ./config/www-2.conf:/usr/local/etc/php-fpm.d/www-2.conf
    - ./config/php.ini:/usr/local/etc/php/php.ini